repos:
  - repo: local
    hooks:
      - id: YAPF
        name: YAPF 🧹
        entry: bash -c 'yapf --in-place *.py'
        language: system
        always_run: true
        pass_filenames: true
      - id: pytest
        name: Unit Tests 🧪
        entry: bash -c 'pytest test_helpers.py'
        language: system
        always_run: true
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
      - id: pretty-format-json

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=100"

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0-a4
    hooks:
      - id: pylint

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
